### ISSUE TITLE
Ruby Group Project

### ISSUE THREAD

**Issue by 187jjay187** [187jjay187/Ruby-Capstone#5]
## Project link:

- [Ruby Group Project link](https://github.com/187jjay187/Ruby-Capstone/projects/1)

### 👤 Maaloum Ely Cheikh

- GitHub: [@githubhandle](https://github.com/maaloum)
- Twitter: [@twitterhandle](https://twitter.com/twitterhandle)
- LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)

###  👤 Soe Sandar Win

- GitHub: [@soesandarwin2201](https://github.com/soesandarwin2201)
- LinkedIn: [LinkedIn](https://www.linkedin.com/in/soe-sandar-win-softwareengineer/)

### 👤 Jerome

- GitHub: [@githubhandle](https://github.com/187jjay187)
- Twitter: [@twitterhandle](https://twitter.com/187jjay187)
- LinkedIn: [LinkedIn](https://linkedin.com/in/jerome-osman-137605a4)

### 👤 Lukman Abdulkarim

- GitHub: [@Lukman](https://github.com/lukman155)
- Twitter: [@Luk, A man](https://twitter.com/lukmanabdulka18)
- LinkedIn: [Lukman Abdulkarim](https://www.linkedin.com/in/lukmanbaba/)

**Comment by m05e5** [comment]
Hi @187jjay187, @maaloum  AND @soesandarwin2201  , 

Good job so far. !
There are some issues that you still need to work on to go to the next project but you are almost there!
![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Highlights


## Required Changes ♻️
* You really did a great job but there are some features you need to improve

- [ ] Hi team. The Kanban board is meant to split down the big tasks into smaller ones to ease the work. So, kindly break down the `1 day` takes into smaller tasks with point allocation (e.g `3pt) instead of days. and keep in mind that 1pt is equal to 1 working hour.

_I'm sure you can do it just keep it up_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MahmoudBakr23** [comment]
Hi Team😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

**Highlights**
- Well done on making the required changes from the previous review. Good luck with the project. 🙏 

Cheers and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
